### PR TITLE
docker64

### PR DESCRIPTION
**Pull request by mrboots123**

### CODE REVIEW

**Comment by Zayelion** [comment]
I initially had issues with ffi-napi. It has issues with threading and we use that for core isolation. So I have to say no on this PR.

What was the trouble you had that required it? Lets see if we can find a solution?

**Comment by purerosefallen** [comment]
I doubt if you really built this Dockerfile before you make this PR. You may have just copied things from our projects.
Firstly, `.ci/libevent-prebuild.sh` is a script in our side which does not exist in *this* repo. Secondly, why do you need to download from `https://cdn01.moecube.com`, rather than the official source? We mirror those packages because of bad network conditions. In addition, it makes no sense to build irrklang in server side.

**Comment by mrboots123** [comment]
Hey everyone thanks for the feedback. @purerosefallen  yes indeed most of the docker commands are coming from your linux command build, which was super helpful in learning how it works. I've modified it enough to run in a linux distro outside of ci, also I've switched out the cdn repos for the original source, my apologies for using yours. As for irrklang build, for some reason it will still try to build it after flagging it. Thank you so much for providing examples in your repository, it is very difficult to piece together information on the ocgcore. @Zayelion ive reverted to buster, but am unable to run the docker command with old ffi.

**Comment by Zayelion** [comment]
I am fairly sure that the core can only be built as 32bit. So you cant push up to node-16 like that.

**Comment by mrboots123** [comment]
this is indeed the 64bit version
Screen Shot 2022-08-21 at 12 03 54 PM
We use this same docker configuration for our ygo sim server which has been tested with all the ocgcore methods.
Screen Shot 2022-08-21 at 12 02 37 PM

**Comment by Zayelion** [comment]
> Hey everyone thanks for the feedback. @purerosefallen yes indeed most of the docker commands are coming from your linux command build, which was super helpful in learning how it works. I've modified it enough to run in a linux distro outside of ci, also I've switched out the cdn repos for the original source, my apologies for using yours. As for irrklang build, for some reason it will still try to build it after flagging it. Thank you so much for providing examples in your repository, it is very difficult to piece together information on the ocgcore. @Zayelion ive reverted to buster, but am unable to run the docker command with old ffi.

If that is the case go ahead and update the FFI dependency and I'll merge it. If it causes an error somewhere we will deal with it at that point. What is important to me is that someone is solving issues and moving development.

**Comment by mrboots123** [comment]
it should be able to run with existing ffi, im not able to test it though

**Pull request merged**
