### PR TITLE
background

### PR DESCRIPTION
**Pull request by LittleBadBad**
enable to chage background and cover image

### CODE REVIEW

**Comment by Zayelion** [comment]
This will cause conflicts with the forum fix in the pipeline. 
There are to many whitespace changes, please undo them
The image should default to what is stored locally and not need to be reset each time.

**Comment by LittleBadBad** [comment]
I used to change the layout of it, and then I didn't know how to withdraw it😂, just drop it.
The key part of the code is I added an intercepter to&nbsp;endpoint_services.js so that every request can carry the admin user's token


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SalvationDevelopment/YGOSalvation-Server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 凌晨0:26
收件人:&nbsp;"SalvationDevelopment/YGOSalvation-Server"<YGOSalvation-Server@noreply.github.com&gt;;
抄送:&nbsp;"卖女孩的小火柴"<1287299719@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SalvationDevelopment/YGOSalvation-Server] background (#413)





 
This will cause conflicts with the forum fix in the pipeline.
 There are to many whitespace changes, please undo them
 The image should default to what is stored locally and not need to be reset each time.

**Comment by Zayelion** [comment]
Going to make some changes to the proxy, there is a branch for that. Keep the fixes coming as you see em.

**Comment by LittleBadBad** [comment]
ok, thanks for your approval😁




张楚研
腾讯校园空间


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SalvationDevelopment/YGOSalvation-Server"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上11:52
收件人:&nbsp;"SalvationDevelopment/YGOSalvation-Server"<YGOSalvation-Server@noreply.github.com&gt;;
抄送:&nbsp;"卖女孩的小火柴"<1287299719@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SalvationDevelopment/YGOSalvation-Server] background (#413)





 
Going to make some changes to the proxy, there is a branch for that. Keep the fixes coming as you see em.

**Pull request merged**
